export enum LEAD_QUESTIONS_GROUP_KEY {
  DATOS_INICIALES = "datosiniciales",
  DOS_O_MAS_DEUDAS = "tienesoadosomasdeudas",
  CORRIENTE_PAGO = "estasalcorrientedepago",
  PODRAS_PAGARLAS = "podraspagarlassinesfuerzo",
  DESDE_CUANDO_NO_PAGAS = "desdecuandonopagastusdeudas",
  DESTINO_PRESTAMOS = "cualhasidoeldestinodelosprestamos",
  TIENES_ANTECEDENTES = "tienesantecedentespenales",
  HAS_CUMPLIDO_LA_PENA = "hascumplidolapena",
  CUMPLIDO_PENA = "hascumplidolapena",
  TIENES_INFRACCIONES = "tienesalgunainfraccionadministrativa",
  TIENES_ESTUDIOS = "eresuniversitariotrabajoprofesional",
  IMPORTE_GLOBAL_DEUDAS = "importeglobaldelasdeudas",
  COMPARTES_TUS_DEUDAS = "compartestusdeudas",
  INGRESOS_PAREJA = "cualessontusingresoslostutupareja",
  CUANTAS_PERSONAS = "cuantaspersonasdependeneconomicamentedeti",
  HIPOTECA_O_ALQUILER = "tieneshipotecavivesdealquiler",
  CUANTO_PAGAS_ALQUILER = "cuantopagasdealquiler",
  CUANTO_PAGAS_HIPOTECA = "cuantopagasdehipoteca",
  CUANTO_TE_FALTA_POR_PAGAR = "cuantotefaltaporpagar",
  CUOTAS_HIPOTECA_AL_DIA = "cuotashipotecaaldia",
  GASTOS_TOTALES = "cualessontusgastostotales",
  CUANTO_DE_CUOTAS = "cuantopagasmensualmentedelascuotas",
  CUANTO_VALE_VIVIENDA = "cuantovalelaviviendahipotecada",
  TIENES_OTROS_BIENES = "tienesotrosbienesactivos",
  VALOR_OTROS_BIENES = "cualeselvalordemercadodetusotrosbienes",
}
